import { PrismaClient, Category, Condition } from '@prisma/client';
import { computeEcoScore } from '../src/ecoScore';

const prisma = new PrismaClient();

type Seed = Omit<
  Parameters<typeof prisma.product.create>[0]['data'],
  'ecoScore'
>;

const products: Seed[] = [
  {
    slug: 'macbook-pro-m3-14',
    name: 'MacBook Pro 14" (M3)',
    brand: 'Apple',
    category: Category.LAPTOP,
    condition: Condition.NEW,
    priceCents: 199900,
    weightKg: 1.55,
    specs: {
      cpu: 'Apple M3',
      cores: 8,
      ramGb: 16,
      storageGb: 512,
      display: '14.2" Liquid Retina XDR',
      ports: ['Thunderbolt4', 'HDMI', 'MagSafe'],
      os: 'macOS',
    },
    repairabilityScore: 4.0,
    energyEfficiency: 9.0,
    carbonKg: 165,
    description: 'Apple Silicon laptop optimized for creative and developer workflows.',
    benchmarks: { cinebench_r23: 12500, geekbench6: 11800 },
  },
  {
    slug: 'macbook-air-m2',
    name: 'MacBook Air (M2)',
    brand: 'Apple',
    category: Category.LAPTOP,
    condition: Condition.REFURBISHED_CERTIFIED,
    priceCents: 99900,
    weightKg: 1.24,
    specs: {
      cpu: 'Apple M2',
      cores: 8,
      ramGb: 8,
      storageGb: 256,
      display: '13.6" Liquid Retina',
      ports: ['Thunderbolt4', 'MagSafe'],
      os: 'macOS',
    },
    repairabilityScore: 4.5,
    energyEfficiency: 9.5,
    carbonKg: 130,
    description: 'Certified refurbished M2 Air — fanless ultraportable.',
    benchmarks: { geekbench6: 9700 },
  },
  {
    slug: 'thinkpad-x1-carbon-g11',
    name: 'ThinkPad X1 Carbon Gen 11',
    brand: 'Lenovo',
    category: Category.LAPTOP,
    condition: Condition.NEW,
    priceCents: 169900,
    weightKg: 1.12,
    specs: {
      cpu: 'Intel Core i7-1365U',
      cores: 10,
      ramGb: 16,
      storageGb: 512,
      display: '14" 2.8K OLED',
      ports: ['Thunderbolt4', 'USB-A', 'HDMI'],
      os: 'Linux/Windows',
    },
    repairabilityScore: 7.5,
    energyEfficiency: 7.0,
    carbonKg: 220,
    description: 'Linux-friendly business ultrabook with strong repairability.',
    benchmarks: { geekbench6: 9200 },
  },
  {
    slug: 'framework-laptop-13',
    name: 'Framework Laptop 13',
    brand: 'Framework',
    category: Category.LAPTOP,
    condition: Condition.NEW,
    priceCents: 129900,
    weightKg: 1.30,
    specs: {
      cpu: 'AMD Ryzen 7 7840U',
      cores: 8,
      ramGb: 16,
      storageGb: 512,
      display: '13.5" 3:2 IPS',
      ports: ['USB-C', 'modular'],
      os: 'Linux/Windows',
    },
    repairabilityScore: 10.0,
    energyEfficiency: 7.5,
    carbonKg: 180,
    description: 'Modular, user-repairable laptop with hot-swappable expansion cards.',
    benchmarks: { geekbench6: 11000 },
  },
  {
    slug: 'dell-u2723qe',
    name: 'Dell UltraSharp U2723QE 27" 4K',
    brand: 'Dell',
    category: Category.MONITOR,
    condition: Condition.NEW,
    priceCents: 64900,
    weightKg: 7.8,
    specs: {
      resolution: '3840x2160',
      refreshHz: 60,
      panel: 'IPS Black',
      ports: ['Thunderbolt4', 'USB-C', 'HDMI', 'DisplayPort'],
      sizeIn: 27,
    },
    repairabilityScore: 6.0,
    energyEfficiency: 8.0,
    carbonKg: 280,
    description: '4K IPS Black panel with Thunderbolt 4 hub built in.',
    benchmarks: {},
  },
  {
    slug: 'lg-ultragear-27gp950',
    name: 'LG UltraGear 27GP950 4K 144Hz',
    brand: 'LG',
    category: Category.MONITOR,
    condition: Condition.NEW,
    priceCents: 79900,
    weightKg: 7.5,
    specs: {
      resolution: '3840x2160',
      refreshHz: 144,
      panel: 'Nano IPS',
      ports: ['HDMI2.1', 'DisplayPort', 'USB-C'],
      sizeIn: 27,
    },
    repairabilityScore: 5.5,
    energyEfficiency: 6.5,
    carbonKg: 320,
    description: 'High-refresh 4K gaming monitor with HDMI 2.1.',
    benchmarks: {},
  },
  {
    slug: 'eizo-flexscan-ev2740x',
    name: 'EIZO FlexScan EV2740X',
    brand: 'EIZO',
    category: Category.MONITOR,
    condition: Condition.NEW,
    priceCents: 109900,
    weightKg: 8.6,
    specs: {
      resolution: '3840x2160',
      refreshHz: 60,
      panel: 'IPS',
      ports: ['USB-C', 'HDMI', 'DisplayPort'],
      sizeIn: 27,
    },
    repairabilityScore: 8.5,
    energyEfficiency: 9.0,
    carbonKg: 240,
    description: 'Office monitor designed for low energy usage and long lifespan.',
    benchmarks: {},
  },
  {
    slug: 'keychron-q1',
    name: 'Keychron Q1 Mechanical Keyboard',
    brand: 'Keychron',
    category: Category.KEYBOARD,
    condition: Condition.NEW,
    priceCents: 17900,
    weightKg: 1.6,
    specs: {
      layout: '75%',
      switches: 'Gateron Pro Brown',
      hotswap: true,
      connectivity: ['USB-C'],
    },
    repairabilityScore: 9.5,
    energyEfficiency: 9.0,
    carbonKg: 25,
    description: 'Hot-swappable aluminum keyboard, fully QMK/VIA programmable.',
    benchmarks: {},
  },
  {
    slug: 'logitech-mx-master-3s',
    name: 'Logitech MX Master 3S',
    brand: 'Logitech',
    category: Category.MOUSE,
    condition: Condition.NEW,
    priceCents: 9999,
    weightKg: 0.14,
    specs: {
      dpi: 8000,
      connectivity: ['Bluetooth', 'USB-C dongle'],
      buttons: 7,
    },
    repairabilityScore: 5.0,
    energyEfficiency: 9.0,
    carbonKg: 12,
    description: 'Productivity mouse with electromagnetic scroll wheel.',
    benchmarks: {},
  },
  {
    slug: 'sony-wh-1000xm5',
    name: 'Sony WH-1000XM5',
    brand: 'Sony',
    category: Category.HEADPHONES,
    condition: Condition.NEW,
    priceCents: 39900,
    weightKg: 0.25,
    specs: {
      driver: '30mm',
      anc: true,
      battery_h: 30,
      connectivity: ['Bluetooth5.2', '3.5mm'],
    },
    repairabilityScore: 4.0,
    energyEfficiency: 8.0,
    carbonKg: 18,
    description: 'Best-in-class noise cancelling headphones.',
    benchmarks: {},
  },
  {
    slug: 'caldigit-ts4',
    name: 'CalDigit TS4 Thunderbolt 4 Dock',
    brand: 'CalDigit',
    category: Category.DOCK,
    condition: Condition.NEW,
    priceCents: 39999,
    weightKg: 0.74,
    specs: {
      ports: ['Thunderbolt4', 'USB-A', 'USB-C', '2.5GbE', 'SD'],
      portsCount: 18,
      supportsThunderbolt4: true,
    },
    repairabilityScore: 6.0,
    energyEfficiency: 7.0,
    carbonKg: 35,
    description: '18-port TB4 dock — workstation-grade hub.',
    benchmarks: {},
  },
  {
    slug: 'anker-577-dock',
    name: 'Anker 577 USB-C Dock',
    brand: 'Anker',
    category: Category.DOCK,
    condition: Condition.NEW,
    priceCents: 24999,
    weightKg: 0.55,
    specs: {
      ports: ['USB-C', 'USB-A', 'HDMI', '1GbE'],
      portsCount: 13,
      supportsThunderbolt4: false,
    },
    repairabilityScore: 6.0,
    energyEfficiency: 7.5,
    carbonKg: 28,
    description: 'Affordable 13-port USB-C dock for typical office workflows.',
    benchmarks: {},
  },
  {
    slug: 'nvidia-rtx-4090',
    name: 'NVIDIA GeForce RTX 4090',
    brand: 'NVIDIA',
    category: Category.GPU,
    condition: Condition.NEW,
    priceCents: 159900,
    weightKg: 2.2,
    specs: {
      vramGb: 24,
      tdpW: 450,
      cudaCores: 16384,
    },
    repairabilityScore: 5.0,
    energyEfficiency: 5.0,
    carbonKg: 410,
    description: 'Flagship GPU for AI training and 4K gaming.',
    benchmarks: { '3dmark_timespy': 36000 },
  },
  {
    slug: 'amd-rx-7900-xtx',
    name: 'AMD Radeon RX 7900 XTX',
    brand: 'AMD',
    category: Category.GPU,
    condition: Condition.NEW,
    priceCents: 99900,
    weightKg: 2.0,
    specs: {
      vramGb: 24,
      tdpW: 355,
      streamProcessors: 6144,
    },
    repairabilityScore: 5.0,
    energyEfficiency: 6.0,
    carbonKg: 360,
    description: 'High-end gaming/creator GPU — strong rasterization performance.',
    benchmarks: { '3dmark_timespy': 30200 },
  },
  {
    slug: 'samsung-990-pro-2tb',
    name: 'Samsung 990 PRO 2TB NVMe',
    brand: 'Samsung',
    category: Category.SSD,
    condition: Condition.NEW,
    priceCents: 19999,
    weightKg: 0.01,
    specs: {
      interface: 'PCIe 4.0 x4',
      capacityGb: 2000,
      seqReadMBs: 7450,
      seqWriteMBs: 6900,
    },
    repairabilityScore: 6.0,
    energyEfficiency: 8.5,
    carbonKg: 8,
    description: 'PCIe Gen4 NVMe, top-tier sequential throughput.',
    benchmarks: { crystaldisk_read: 7450 },
  },
  {
    slug: 'wd-black-sn850x-2tb',
    name: 'WD_BLACK SN850X 2TB',
    brand: 'Western Digital',
    category: Category.SSD,
    condition: Condition.NEW,
    priceCents: 16999,
    weightKg: 0.01,
    specs: {
      interface: 'PCIe 4.0 x4',
      capacityGb: 2000,
      seqReadMBs: 7300,
      seqWriteMBs: 6600,
    },
    repairabilityScore: 6.0,
    energyEfficiency: 8.0,
    carbonKg: 9,
    description: 'PCIe Gen4 NVMe — strong gaming load times.',
    benchmarks: { crystaldisk_read: 7300 },
  },
  {
    slug: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    brand: 'Apple',
    category: Category.PHONE,
    condition: Condition.NEW,
    priceCents: 99900,
    weightKg: 0.187,
    specs: {
      chip: 'A17 Pro',
      ramGb: 8,
      storageGb: 256,
      display: '6.1" OLED 120Hz',
      port: 'USB-C',
    },
    repairabilityScore: 4.5,
    energyEfficiency: 9.0,
    carbonKg: 65,
    description: 'Titanium frame iPhone with A17 Pro chip.',
    benchmarks: { geekbench6: 7200 },
  },
  {
    slug: 'pixel-8-pro',
    name: 'Google Pixel 8 Pro',
    brand: 'Google',
    category: Category.PHONE,
    condition: Condition.NEW,
    priceCents: 99900,
    weightKg: 0.213,
    specs: {
      chip: 'Tensor G3',
      ramGb: 12,
      storageGb: 256,
      display: '6.7" OLED 120Hz',
      port: 'USB-C',
    },
    repairabilityScore: 6.5,
    energyEfficiency: 8.0,
    carbonKg: 75,
    description: '7-year update support — long lifespan flagship.',
    benchmarks: { geekbench6: 5400 },
  },
  {
    slug: 'fairphone-5',
    name: 'Fairphone 5',
    brand: 'Fairphone',
    category: Category.PHONE,
    condition: Condition.NEW,
    priceCents: 79900,
    weightKg: 0.212,
    specs: {
      chip: 'Qualcomm QCM6490',
      ramGb: 8,
      storageGb: 256,
      display: '6.46" OLED 90Hz',
      port: 'USB-C',
    },
    repairabilityScore: 10.0,
    energyEfficiency: 7.5,
    carbonKg: 40,
    description: 'Modular, user-repairable phone with 8 years of OS updates.',
    benchmarks: { geekbench6: 2900 },
  },
  {
    slug: 'ipad-pro-m4-11',
    name: 'iPad Pro 11" (M4)',
    brand: 'Apple',
    category: Category.TABLET,
    condition: Condition.NEW,
    priceCents: 99900,
    weightKg: 0.444,
    specs: {
      chip: 'Apple M4',
      ramGb: 8,
      storageGb: 256,
      display: '11" Tandem OLED 120Hz',
      port: 'Thunderbolt4',
    },
    repairabilityScore: 3.5,
    energyEfficiency: 9.5,
    carbonKg: 95,
    description: 'M4 iPad with Tandem OLED display.',
    benchmarks: { geekbench6: 14000 },
  },
];

async function main() {
  for (const p of products) {
    const ecoScore = computeEcoScore({
      repairabilityScore: p.repairabilityScore as number,
      energyEfficiency: p.energyEfficiency as number,
      carbonKg: p.carbonKg as number,
    });
    await prisma.product.upsert({
      where: { slug: p.slug as string },
      update: { ...p, ecoScore },
      create: { ...p, ecoScore },
    });
  }
  const count = await prisma.product.count();
  console.log(`seeded ${count} products`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
